# Generated by Django 2.2.5 on 2019-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESPECI_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speci', models.CharField(max_length=80)),
                ('codigo_oaci', models.CharField(max_length=80)),
                ('dia_obser', models.CharField(max_length=80)),
                ('hora_observ', models.CharField(max_length=80)),
                ('obser_autom', models.CharField(max_length=80)),
                ('medida_viento', models.CharField(max_length=80)),
                ('visibilidad_horiz', models.CharField(max_length=80)),
                ('alcance_visual', models.CharField(max_length=80)),
                ('tiempo_presente', models.CharField(max_length=80)),
                ('capa_nube', models.CharField(max_length=80)),
                ('temperatura', models.CharField(max_length=80)),
                ('temperatura_rocio', models.CharField(max_length=80)),
                ('qnh', models.CharField(max_length=80)),
                ('estado_pista', models.CharField(max_length=80)),
                ('comentario', models.CharField(max_length=80)),
                ('nubes_opcion', models.CharField(max_length=80)),
                ('presion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='METAR_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metar', models.CharField(max_length=5)),
                ('codigo_oaci', models.CharField(max_length=4)),
                ('dia_obser', models.SmallIntegerField()),
                ('hora_observ', models.SmallIntegerField()),
                ('viento_direc', models.SmallIntegerField()),
                ('viento_intens', models.SmallIntegerField()),
                ('rafaga', models.SmallIntegerField()),
                ('viento_variable_1', models.CharField(max_length=7)),
                ('visibilidad_horiz_1', models.SmallIntegerField()),
                ('visibilidad_horiz_2', models.SmallIntegerField()),
                ('direccion_predomin', models.CharField(max_length=2)),
                ('tiempo_presente_1', models.CharField(max_length=6)),
                ('tiempo_presente_2', models.CharField(max_length=6)),
                ('tiempo_presente_3', models.CharField(max_length=6)),
                ('capa_nube', models.CharField(max_length=80)),
                ('temperatura', models.SmallIntegerField()),
                ('temperatura_rocio', models.SmallIntegerField()),
                ('qnh', models.CharField(max_length=80)),
                ('humedad_relat', models.SmallIntegerField()),
                ('pasos_cordillera', models.CharField(max_length=5)),
                ('comentario', models.CharField(max_length=80)),
                ('estado_pista', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TAF_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taf', models.CharField(max_length=80)),
                ('codigo_oaci', models.CharField(max_length=80)),
                ('pediodo_validez', models.CharField(max_length=80)),
                ('viento', models.CharField(max_length=80)),
                ('vsibilidad', models.CharField(max_length=80)),
                ('precipitacion', models.CharField(max_length=80)),
                ('capa_nublada', models.CharField(max_length=80)),
                ('tempo', models.CharField(max_length=80)),
                ('nieve', models.CharField(max_length=80)),
                ('cambio_viento', models.CharField(max_length=80)),
                ('proximo_pronostico', models.CharField(max_length=80)),
            ],
        ),
    ]
