# Generated by Django 2.2.5 on 2019-11-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metar_trafico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_amhs', models.CharField(max_length=30)),
                ('fecha_llegada', models.DateField()),
                ('hora_amhs', models.CharField(max_length=10)),
                ('prioridad', models.CharField(max_length=2)),
                ('estacion', models.CharField(max_length=50)),
                ('hora_clima', models.CharField(max_length=60)),
                ('texto', models.CharField(max_length=1000)),
                ('visto', models.BooleanField(default=False)),
            ],
        ),
    ]
